function x = forward_kin(q)
  %   forward_kin calculats the postion row vector/matrix of the tool
  %   in project 1
  %     H,L,l1,l2 are global parameters of the linkages/
  %     The vector q is a row/matrix vector of the joints valuse were
  %     angels are in degres and distance is in meters
  global H L l1 l2;
  x = zeros(size(q,1),3);
  % Calulating x:
  for i=1:size(x,1)
      % The transformation matrixs:
      theta1 = q(i,1);
      theta2 = q(i,2);
      d3 = q(i,3);
%       theta4 = q(i,4);
%       theta5 = q(i,5);
      A01 = [...
          cos(theta1) -sin(theta1) 0 0;...
          sin(theta1) cos(theta1) 0 0;...
          0 0 1 H;...
          0 0 0 1];
      A12 = [...
          1 0 0 L;...
          0 cos(theta2) -sin(theta2) 0;...
          0 sin(theta2) cos(theta2) 0;...
          0 0 0 1];
      A23 = [...
          1 0 0 0;...
          0 1 0 0;...
          0 0 1 d3;...
          0 0 0 1];
%       A34 = [...
%           cos(theta4) -sin(theta4) 0 0;...
%           sin(theta4) cos(theta4) 0 0;...
%           0 0 1 l1;...
%           0 0 0 1];
%       A4t = [...
%           cos(theta5) 0 -sin(theta5) -sin(theta5)*l2;...
%           0 1 0 0;...
%           sin(theta5) 0 cos(theta5) cos(theta5)*l2;...
%           0 0 0 1];
      % Calculating the transformation matrix
%       A0t = A01*A12*A23*A34*A4t;
       A0t = A01*A12*A23;
      % Calculating x
      x(i,:) = A0t(1:3,4).';
  end
end